### ISSUE TITLE
Is subscribing /clock and /tf_static possible?

### ISSUE THREAD

**Issue by bibistellar** [lambdaprime/jros2client#12]
Hello,I try to use jros2client to subscribe /clock and /tf_static topic, but no output I can get,while subscribing /tf works. /clock topic comes from gazebo and its message type is rosgraph_msgs/msg/Clock.

**Comment by lambdaprime** [comment]
Hi @bibistellar ,

Thanks for using **jrosclient**

1.
**jros2client** comes with basic set of messages (see [jros2messages](http://portal2.atwebpages.com/jrosclient/javadoc/jros2messages/index.html) [jrosmessages](http://portal2.atwebpages.com/jrosclient/javadoc/jrosmessages/index.html)) and rosgraph_msgs/msg/Clock is not one of them.
Missing messages you can [define manually](http://portal2.atwebpages.com/jrosclient/Defining_messages.html) or using [msgmonster app](https://github.com/pinorobotics/msgmonster)

2.
The type of /tf_static is tf2_msgs/msg/TFMessage

```
ubuntu@humble ~ % ros2 topic info /tf_static
ros2 topic info /tf_static
Type: tf2_msgs/msg/TFMessage
Publisher count: 2
Subscription count: 5
```

TFMessage is part of [jros2tf2](http://pinoweb.freetzi.com/jrostf2/javadoc/jros2tf2/jros2tf2/pinorobotics/jros2tf2/tf2_msgs/TFMessage.html) so you can use it from there

Regards,

**Comment by bibistellar** [comment]
### 
I have defined a Java message and set up a subscriber to the `/clock` topic using JRos2Client. Despite this setup, there are no messages being output to the terminal.

### Code

**ClockMessage.java:**

```java
import java.util.Objects;
import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.xfunction.XJson;

/**
 * Definition for rosgraph_msgs/Clock
 */
@MessageMetadata(name = ClockMessage.NAME)
public class ClockMessage implements Message {
    static final String NAME = "rosgraph_msgs/Clock";

    /**
     * This message communicates the current time.
     * For more information, see https://design.ros2.org/articles/clock_and_time.html.
     */
    public TimeMessage clock = new TimeMessage();

    public ClockMessage withClock(TimeMessage clock) {
        this.clock = clock;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clock);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        ClockMessage other = (ClockMessage) obj;
        return Objects.equals(clock, other.clock);
    }

    @Override
    public String toString() {
        return XJson.asString("clock", clock);
    }
}
```

**TimeMessage.java:**

```java
import java.util.Objects;
import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.xfunction.XJson;
import id.jrosmessages.std_msgs.Int32Message;

/**
 * Definition for builtin_interfaces/Time
 *
 * <p>This message communicates ROS Time defined here:
 * https://design.ros2.org/articles/clock_and_time.html
 */
@MessageMetadata(name = TimeMessage.NAME, fields = {"sec", "nanosec"})
public class TimeMessage implements Message {
    static final String NAME = "builtin_interfaces/Time";

    public Int32Message sec = new Int32Message();
    public int nanosec;

    public TimeMessage withSec(Int32Message sec) {
        this.sec = sec;
        return this;
    }

    public TimeMessage withNanosec(int nanosec) {
        this.nanosec = nanosec;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(sec, nanosec);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        TimeMessage other = (TimeMessage) obj;
        return Objects.equals(sec, other.sec) && nanosec == other.nanosec;
    }

    @Override
    public String toString() {
        return XJson.asString("sec", sec, "nanosec", nanosec);
    }
}
```

**Test Code:**

```java
import id.jros2client.JRos2Client;
import id.jros2client.JRos2ClientConfiguration;
import id.jros2client.JRos2ClientFactory;
import id.jrosclient.TopicSubscriber;
import pinorobotics.rtpstalk.RtpsTalkConfiguration;

public class test {
    public static void main(String[] args) {
        RtpsTalkConfiguration config = new RtpsTalkConfiguration.Builder()
            .domainId(1)
            .build();
        JRos2ClientConfiguration clientConfig = new JRos2ClientConfiguration.Builder().rtpsTalkConfiguration(config)
            .build();
        JRos2Client client = new JRos2ClientFactory().createClient(clientConfig);

        try {
            client.subscribe(new TopicSubscriber<ClockMessage>(ClockMessage.class, "/clock") {
                @Override
                public void onNext(ClockMessage item) {
                    System.out.println(item);
                    getSubscription().get().request(1);
                }
            });
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
```

### Expected Behavior
I expected the current time message to be printed to the terminal as they are published on the `/clock` topic.

### Actual Behavior
No output is received in the terminal.

Any insights or suggestions would be greatly appreciated.
```

**Comment by lambdaprime** [comment]
Hi @bibistellar 

We tried following Clock test publisher and then code you provided:

```
import rclpy
from rclpy.node import Node
from rosgraph_msgs.msg import Clock


class MinimalPublisher(Node):

    def __init__(self):
        super().__init__('clock')
        self.publisher_ = self.create_publisher(Clock, 'clock', 10)
        timer_period = 0.5  # seconds
        self.timer = self.create_timer(timer_period, self.timer_callback)
        self.i = 0

    def timer_callback(self):
        sim_clock = Clock()
        sim_clock.clock.sec = 123
        self.publisher_.publish(sim_clock)
        self.get_logger().info('Publishing: "%s"' % sim_clock)
        self.i += 1


def main(args=None):
    rclpy.init(args=args)

    minimal_publisher = MinimalPublisher()

    rclpy.spin(minimal_publisher)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    minimal_publisher.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

Subscriber could connect and started to receive the messages:

{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }
{ "clock": { "sec": { "data": 123 }, "nanosec": 0 } }


If you specify ".domainId(1)" please make sure that ROS RMW also configured to use that domainId (by default it may not).

If problem still persist please send [debug logs](http://portal2.atwebpages.com/jrosclient/#Logging)

**Comment by bibistellar** [comment]
I identified that the QoS settings were not compatible between the publisher and subscriber. Here are the details:

## Publisher QoS Settings

**Node Name:** `gazebo`  
**Node Namespace:** `/`  
**Topic Type:** `rosgraph_msgs/msg/Clock`  
**Endpoint Type:** `PUBLISHER`  
**GID:** `01.0f.32.30.e8.77.aa.99.00.00.00.00.00.00.12.03.00.00.00.00.00.00.00.00`  

**QoS Profile:**
- **Reliability:** BEST_EFFORT
- **History (Depth):** UNKNOWN
- **Durability:** VOLATILE
- **Lifespan:** Infinite
- **Deadline:** Infinite
- **Liveliness:** AUTOMATIC
- **Liveliness Lease Duration:** Infinite

## Subscriber QoS Settings

**Node Name:** `_CREATED_BY_BARE_DDS_APP_`  
**Node Namespace:** `_CREATED_BY_BARE_DDS_APP_`  
**Topic Type:** `rosgraph_msgs/msg/Clock`  
**Endpoint Type:** `SUBSCRIPTION`  
**GID:** `ca.fe.4c.5d.aa.f1.58.b7.b6.06.16.c1.00.00.01.04.00.00.00.00.00.00.00.00`  

**QoS Profile:**
- **Reliability:** RELIABLE
- **History (Depth):** UNKNOWN
- **Durability:** VOLATILE
- **Lifespan:** Infinite
- **Deadline:** Infinite
- **Liveliness:** AUTOMATIC
- **Liveliness Lease Duration:** Infinite

The reliability should be set to `BEST_EFFORT` instead of `RELIABLE`. However, I encountered an issue while attempting to set the QoS Reliability in the `jros2client` using the code below, the reliability is still `RELIABLE` not `BEST_EFFORT`. Could you help me resolve this?

```java
public class test {
    public static void main(String[] args) {
        RtpsTalkConfiguration config = new RtpsTalkConfiguration.Builder()
                .domainId(1)
                .builtinEndpointQos(EndpointQos.BEST_EFFORT_PARTICIPANT_MESSAGE_DATA_READER)
                .build();
        JRos2ClientConfiguration clientConfig = new JRos2ClientConfiguration.Builder().rtpsTalkConfiguration(config)
                .build();
        JRos2Client client = new JRos2ClientFactory().createClient(clientConfig);
        //
        try {
            client.subscribe(new TopicSubscriber<ClockMessage>(ClockMessage.class, "/clock") {

                @Override
                public void onNext(ClockMessage item) {
                    System.out.println(item);
                    getSubscription().get().request(1);
                }
            });
        } catch (Exception e) {
            System.out.println(e);
        }

    }
}
```

---

**Comment by lambdaprime** [comment]
Hi @bibistellar ,

Thank you for the analysis.

We added [Troubleshooting](http://portal2.atwebpages.com/jrosclient/Quick_Start_jros2client.html#Troubleshooting) paragraph to help users identify the issue.

In the code you use:

```
.builtinEndpointQos(EndpointQos.BEST_EFFORT_PARTICIPANT_MESSAGE_DATA_READER)
```

This line changes the QOS policy for the RTPS builtin endpoints (these are RTPS internal topics) and not for ROS subscriber to /clock. This is why it still did not work.

As of now **jros2client** does not allow users to change the QOS policy of a subscriber. We plan to add it in a couple of weeks.

Regards,

**Comment by lambdaprime** [comment]
Hi @bibistellar ,

We are still working on QOS policy support for subscribers.

Regards,

**Comment by lambdaprime** [comment]
Hi @bibistellar ,

The fix is ready and will be included in the next version we plan to release.
Until then you can use [prerelease version](https://github.com/lambdaprime/jros2client/releases/tag/snapshot9)
Users can redefine QOS policies using overloaded version of subscribe() method.
You will need to [install it manually](http://portal2.atwebpages.com/jrosclient/Quick_Start_jros2client.html#Installing%20manually)

Regards,

**Comment by lambdaprime** [comment]
Hi @bibistellar,

We just published a [new v9 release](https://github.com/lambdaprime/jros2client/blob/main/jros2client/release/CHANGELOG.md). It has [new extended subscribe method](http://portal2.atwebpages.com/jrosclient/javadoc/jros2client/jros2client/id/jros2client/JRos2Client.html#subscribe(id.jros2client.qos.SubscriberQos,id.jrosclient.TopicSubscriber)) which can be used to specify which QOS to use.

Regards,
