### ISSUE TITLE
How to handle unmapped primitives

### ISSUE THREAD

**Issue by marlow-fawn** [lambdaprime/jros2client#13]
Is there any documentation for how to handle messages that pass standard ROS primitives that aren't in the jrosclient mapping? My specific use case is Int16, though the ability to use other signed/unsigned primitives would be great.

**Comment by lambdaprime** [comment]
Hi @marlow-fawn ,

Thanks for using **jrosclient**

We updated [documentation with new types](http://portal2.atwebpages.com/jrosclient/Defining_messages.html) (including int16)

And also added them to upcoming version of **msgmonster**

Regards,
